name: recru_task_pm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  intl: ^0.19.0
  flutter_svg: ^2.0.15
  get_it: ^8.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  gap: ^3.0.1
  either_dart: ^1.0.0
  rxdart: ^0.28.0
  mocktail: ^1.0.4
  golden_test: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  assets:
    - assets/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  uses-material-design: true
  generate: true
